version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 5P^2@i#^D638@N3#J#T4
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: 5P^2@i#^D638@N3#J#T4

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 5P^2@i#^D638@N3#J#T4
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - 'C:\Users\mateu\repos\wp\clear:/var/www/html/'
      - 'C:\Users\mateu\repos\wp\wp-content:/var/www/html/wp-content'
volumes:
  db_data: {}
